<a href="https://colab.research.google.com/github/arnavxyz/scaler_numpy/blob/main/Numpy_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
x = np.arange(16).reshape(4,4)

In [ ]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
np.hsplit(x,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [ ]:
np.hsplit(x, np.array([3,6]))

[array([[ 0,  1,  2],
        [ 4,  5,  6],
        [ 8,  9, 10],
        [12, 13, 14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]]),
 array([], shape=(4, 0), dtype=int64)]

In [ ]:
np.hsplit(x, ([4]))

[array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]]),
 array([], shape=(4, 0), dtype=int64)]

In [ ]:
np.hsplit(x, ([1,2]))

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [ ]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
np.vsplit(x,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [ ]:
np.vsplit(x, np.array([3]))

[array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

In [ ]:
np.vsplit(x, ([1,3]))

[array([[0, 1, 2, 3]]),
 array([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

In [ ]:
np.vsplit(x, ([1,6]))

[array([[0, 1, 2, 3]]),
 array([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]]),
 array([], shape=(0, 4), dtype=int64)]

In [ ]:
np.vsplit(x, ([1,4]))

[array([[0, 1, 2, 3]]),
 array([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]]),
 array([], shape=(0, 4), dtype=int64)]

In [ ]:
# Note: If splitting index isgreater than no. of columns in hsplit or no.of rows in vsplit, we will get an empty subarray at the end

In [ ]:
a = np.arange(5).reshape(5,1)

In [ ]:
a

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [ ]:
b = np.arange(15).reshape(5,3)

In [ ]:
np.hstack([a,b])

array([[ 0,  0,  1,  2],
       [ 1,  3,  4,  5],
       [ 2,  6,  7,  8],
       [ 3,  9, 10, 11],
       [ 4, 12, 13, 14]])

In [ ]:
c = np.arange(5)

In [ ]:
d = np.arange(2,7)

In [ ]:
c

array([0, 1, 2, 3, 4])

In [ ]:
d

array([2, 3, 4, 5, 6])

In [ ]:
np.vstack([c,d])

array([[0, 1, 2, 3, 4],
       [2, 3, 4, 5, 6]])

In [ ]:
np.vstack([c,d,d])

array([[0, 1, 2, 3, 4],
       [2, 3, 4, 5, 6],
       [2, 3, 4, 5, 6]])

In [ ]:
d = np.array([1,3,5,7,9,11,15])

In [ ]:
np.vstack([c,d])

ValueError: ignored

In [ ]:
a = np.array([[1], [2], [3]])
b = np.array([[4], [5], [6]])

In [ ]:
a

array([[1],
       [2],
       [3]])

In [ ]:
b

array([[4],
       [5],
       [6]])

In [ ]:
np.vstack([a,b])

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [ ]:
np.hstack([a,b])

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
# np.concatenate does both vertical and horizontal stacking
# axis = 0: vstack (row stacking, one below other)
# axis = 1: hstack (column stacking, one beside other)

In [ ]:
a = np.array([[1,2,3]])

In [ ]:
a

array([[1, 2, 3]])

In [ ]:
b = np.array([[1,2,3],[4,5,6]])

In [ ]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.concatenate([a,b], axis=0) #vstack

array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 6]])

In [ ]:
a = np.arange(6).reshape(3,2)

In [ ]:
b = np.arange(9).reshape(3,3)

In [ ]:
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [ ]:
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
np.concatenate([a,b], axis=1) # axis=1 -> hstack

array([[0, 1, 0, 1, 2],
       [2, 3, 3, 4, 5],
       [4, 5, 6, 7, 8]])

In [ ]:
np.concatenate([a,b], axis=None) # Flattens individual numpy arrays to 1D, then joins and converts to 1D

array([0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])

In [ ]:
a

array([[1, 2],
       [3, 4]])

In [ ]:
b

array([[5, 6]])

In [ ]:
a.shape

(2, 2)

In [ ]:
b.shape

(1, 2)

In [ ]:
b.T

array([[5],
       [6]])

In [ ]:
np.concatenate((a, b.T), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])