<a href="https://colab.research.google.com/github/arnavxyz/scaler_numpy/blob/main/Numpy_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
a = np.array(range(16)) # == np.arange(16)

In [ ]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [ ]:
a.ndim

1

In [ ]:
a.shape

(16,)

In [ ]:
'''
How can we convert this 1D numpy array to 2D?
'''

'\nHow can we convert this 1D numpy array to 2D?\n'

In [ ]:
a.reshape(8,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])

In [ ]:
a1 = a.reshape(8,2)

In [ ]:
a1

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])

In [ ]:
a1.shape

(8, 2)

In [ ]:
a2 = np.reshape(a,[8,2])

In [ ]:
a2

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])

In [ ]:
a2.shape

(8, 2)

In [ ]:
a2.ndim

2

In [ ]:
a2.size

16

In [ ]:
a.reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
a.reshape(4,5)

ValueError: ignored

In [ ]:
a.reshape(2,2,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [ ]:
a.reshape(8,-1) # Numpy interpretes the other dimension marked as -1 :  16/8 = 2

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])

In [ ]:
a.reshape(-1,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
a.reshape(-1,-1)

ValueError: ignored

In [ ]:
a.reshape(2,2,-1)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [ ]:
a.reshape(2,-1,-1)

ValueError: ignored

In [ ]:
a1.shape

(8, 2)

In [ ]:
len(a1)

8

In [ ]:
len(a1[0])

2

In [ ]:
b = np.arange(12).reshape(3,4) # g (f(x)) where f(x) = x ** 2 and g(x) = x ** 3 -> x ** 6

In [ ]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
b.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [ ]:
b.T.shape

(4, 3)

In [ ]:
a = np.array([1,2,3, [4,5], [6,7,8], 9, 0])

<ipython-input-35-cf56452bb73c>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  a = np.array([1,2,3, [4,5], [6,7,8], 9, 0])


In [ ]:
a.ndim

1

In [ ]:
a.shape

(7,)

In [ ]:
a.dtype

dtype('O')

In [ ]:
a ** 2

TypeError: ignored

In [ ]:
a[4][0]

6

In [ ]:
m1 = np.arange(1,10).reshape(3,3)

In [ ]:
m1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
m1[1,1]

5

In [ ]:
m1[1][1]

5

In [ ]:
m1 = np.array([100,200,300,400,500,600])

In [ ]:
m1[2,3]

IndexError: ignored

In [ ]:
m1[[2,3]]

array([300, 400])

In [ ]:
m1[[2,3,4,1,2,2]]

array([300, 400, 500, 200, 300, 300])

In [ ]:
m1 = np.arange(9).reshape(3,3)

In [ ]:
m1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
m1[[0,1,2],[0,1,2]] # Please note the sequence of commas

array([0, 4, 8])

In [ ]:
m1[[0,2],[1,1]]  # [0,1], [2,1]

array([1, 7])

In [ ]:
# Slicing operation

In [ ]:
m1 = np.arange(12).reshape(3,4)

In [ ]:
m1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
m1[:2] # gives first 2 rows

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [ ]:
m1[:, :2] # gives data for first 2 columns

array([[0, 1],
       [4, 5],
       [8, 9]])

In [ ]:
m1[,:2]

SyntaxError: ignored

In [ ]:
m1[:,1:3] # gives 2nd and 3rd column

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]])

In [ ]:
a = np.array([1,2,3,4,5])
b = np.array([8,7,6])
a[3:] = b[::-2]

In [ ]:
a

array([1, 2, 3, 6, 8])

In [ ]:
m1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
m1 < 6

array([[ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False]])

In [ ]:
m1[m1<6]

array([0, 1, 2, 3, 4, 5])

In [ ]:
m1[m1>6]

array([ 7,  8,  9, 10, 11])

In [ ]:
a = np.array([0,1,2,3,4,5])
mask = (a%2 == 0)
a[mask] = -1

In [ ]:
a

array([-1,  1, -1,  3, -1,  5])

In [ ]:
mask

array([ True, False,  True, False,  True, False])

In [ ]:
# Aggregate functions

In [ ]:
a = np.arange(1,11)

In [ ]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
np.sum(a)

55

In [ ]:
a.sum()

55

In [ ]:
np.mean(a) # Mean or average value

5.5

In [ ]:
np.min(a) # Minimum value

1

In [ ]:
np.max(a) # Maximum value

10

In [ ]:
np.median(a)

5.5

In [ ]:
np.mode(a)

AttributeError: ignored

In [ ]:
a = np.arange(12).reshape(3,4)

In [ ]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
np.sum(a)

66

In [ ]:
np.sum(a, axis = 0) # Changes will happen along the vertical axis, basically column wise sum for 2D arrays

array([12, 15, 18, 21])

In [ ]:
np.sum(a, axis=1) # Rowwise sum for 2D arrays, summing of values in horizontal directoion

array([ 6, 22, 38])

In [ ]:
'''Imagine you have a shopping list with items you need to buy, but you're not sure if you have enough money to buy everything. You want to check if there's at least one item on your list that you can afford.'''

In [ ]:
prices = np.array([50,45,25,20,35])

In [ ]:
budget = 30

In [ ]:
# Check if we can afford one item
can_afford = np.any(prices <= budget) # Always returns a boolean (True/False value)

In [ ]:
can_afford

True

In [ ]:
a = np.array([0,2,3])
b = np.array([1,3,5])
a >= b

array([False, False, False])

In [ ]:
Now, let's consider a scenario where you have a list of chores, and you want to make sure all the chores are completed before you can play video games.

In [ ]:
chores = np.array([1,1,1,1,0])

In [ ]:
np.all(chores) # Check if all chores are done. Boolean result

False

In [ ]:
a = np.array([1, 2, 3, 2])
b = np.array([2, 2, 3, 2])
c = np.array([6, 4, 4, 5])

((a <= b) & (b <= c)).all()

True

In [ ]:
arr = np.array([-3,4,27,34,-2, 0, -45,-11,4, 0 ])

In [ ]:
arr[arr > 0] = 1

In [ ]:
arr [arr < 0] = -1

In [ ]:
arr

array([-1,  1,  1,  1, -1,  0, -1, -1,  1,  0])

In [ ]:
Suppose you have a list of product prices, and you want to apply a 10% discount to all products with prices above $50.

SyntaxError: ignored

In [ ]:
prices = np.array([45, 55, 60, 75, 40, 90, -5])

In [ ]:
discounted_prices = np.where(prices > 50, prices * 0.9, prices)

In [ ]:
discounted_prices

array([45. , 49.5, 54. , 67.5, 40. , 81. , -5. ])

In [ ]:
discounted_prices = np.where(prices > 50, prices * 0.9, prices * 0.8, prices)

TypeError: ignored

In [ ]:
discounted_prices = np.where(prices > 50)

In [ ]:
discounted_prices

(array([1, 2, 3, 5]),)

In [ ]:
np.where(prices) # Returns indices of elements > 0

(array([0, 1, 2, 3, 4, 5, 6]),)

In [ ]:
'''
Use Case: Fitness data analysis
Data:https://drive.google.com/file/d/1Uxwd4H-tfM64giRS1VExMpQXKtBBtuP0/view?usp=sharing
'''

'\nUse Case: Fitness data analysis\nData:https://drive.google.com/file/d/1Uxwd4H-tfM64giRS1VExMpQXKtBBtuP0/view?usp=sharing\n'

In [ ]:
'''
Date
Step Count
Mood (Categorical)
Calories Burned
Hours of sleep
Feeling Active (Categorical)
'''

'\nDate\nStep Count\nMood (Categorical)\nCalories Burned\nHours of sleep\nFeeling Active (Categorical)\n'