<a href="https://colab.research.google.com/github/arnavxyz/scaler_numpy/blob/main/Numpy4_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

a = np.arange(4)

In [ ]:
a

array([0, 1, 2, 3])

In [ ]:
b = a.reshape(2,2)

In [ ]:
b

array([[0, 1],
       [2, 3]])

In [ ]:
a[0] = 100

In [ ]:
a

array([100,   1,   2,   3])

In [ ]:
b

array([[100,   1],
       [  2,   3]])

In [ ]:
np.shares_memory(a,b)

True

In [ ]:
c = a + 2 # Separate copy. More permanent change in data. Deep Copy

In [ ]:
c

array([102,   3,   4,   5])

In [ ]:
a[0] = 100

In [ ]:
c

array([102,   3,   4,   5])

In [ ]:
'''
Shallow Copy: Numpy is able to use same data for simpler operations like reshape
Deep Copy -> Creates a copy of data where operations make more permanent changes to the data
'''

'\nShallow Copy: Numpy is able to use same data for simpler operations like reshape\nDeep Copy -> Creates a copy of data where operations make more permanent changes to the data\n'

In [ ]:
np.shares_memory(a,c)

False

In [ ]:
a = np.arange(10)

In [ ]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
b = a[::2]

In [ ]:
b

array([0, 2, 4, 6, 8])

In [ ]:
np.shares_memory(a,b)

True

In [ ]:
b = a + 2

In [ ]:
np.shares_memory(a,b)

False

In [ ]:
a = np.array([0,1,2,3,4,5])
b = a[a%1 == 0]

b[0] = 10
print(a[:2])

[0 1]


In [ ]:
np.shares_memory(a,b) #Masking operation is a deep copy operation

False

In [ ]:
arr = np.arange(10)

In [ ]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#Shallow Copy

In [ ]:
view_arr = arr.view() #Returns view of original array. Any changes made in new array will be reflected in the original array

In [ ]:
view_arr[4] = 420

In [ ]:
view_arr

array([  0,   1,   2,   3, 420,   5,   6,   7,   8,   9])

In [ ]:
np.shares_memory(arr, view_arr)

True

In [ ]:
# Deep Copy

In [ ]:
arr = np.arange(10)

In [ ]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
copy_arr = arr.copy()

In [ ]:
copy_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
copy_arr[3] = 45

In [ ]:
copy_arr

array([ 0,  1,  2, 45,  4,  5,  6,  7,  8,  9])

In [ ]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
'''
.copy() returns deep copy of an array except for object dtype
copy.deepcopy() returns deep copy of an array
'''

'\n.copy() returns deep copy of an array except for object dtype\ncopy.deepcopy() returns deep copy of an array\n'

In [ ]:
'''
Documentation (.copy()):
https://numpy.org/doc/stable/reference/generated/numpy.ndarray.copy.html#numpy.ndarray.copy

Documentation: (np.copy()):
https://numpy.org/doc/stable/reference/generated/numpy.copy.html
'''

'\nDocumentation (.copy()):\nhttps://numpy.org/doc/stable/reference/generated/numpy.ndarray.copy.html#numpy.ndarray.copy\n\nDocumentation: (np.copy()):\nhttps://numpy.org/doc/stable/reference/generated/numpy.copy.html\n'

In [ ]:
\

SyntaxError: ignored

In [ ]:
#Array Splitting

In [ ]:
x = np.arange(9)

In [ ]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
np.split(x,3) # Equal sized splits of the array

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

In [ ]:
#Important Requisite:
# No. of elements in the array should be divisible by the no. of sections

In [ ]:
np.split(x,2)

ValueError: ignored

In [ ]:
np.split(x, [3,5,6]) # Unequal sized splits

[array([0, 1, 2]), array([3, 4]), array([5]), array([6, 7, 8])]