<a href="https://colab.research.google.com/github/arnavxyz/scaler_numpy/blob/main/Numpy_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
x = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [ ]:
x[[0][0]] # not equivalent to x[0][0]

array([1, 2, 3])

In [ ]:
x[[0],[0]]

array([1])

In [ ]:
x[[0,1],[1,2]] # x[0,1] x[1,2]

array([2, 6])

In [ ]:
y = [-1,-5,6,7,0,7,-9,3,0]

In [ ]:
np.where(y) # Finds indices of non-zero elements (includes positive & negative values)

(array([0, 1, 2, 3, 5, 6, 7]),)

In [ ]:
arr = np.arange(12).reshape(-1,4)

In [ ]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
arr.shape

(3, 4)

In [ ]:
## Sorting of numpy arrays

In [ ]:
a = np.array([4, 7, 0, 3, 8, 2, 5, 1, 6, 9])

In [ ]:
a

array([4, 7, 0, 3, 8, 2, 5, 1, 6, 9])

In [ ]:
np.sort(a) #Not an inplace operation. So no change is reflected in original array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a

array([4, 7, 0, 3, 8, 2, 5, 1, 6, 9])

In [ ]:
b = np.sort(a)

In [ ]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a.argsort() # Not inplace. Returns indices of array a in sorted order

array([2, 7, 5, 3, 0, 6, 8, 1, 4, 9])

In [ ]:
a

array([4, 7, 0, 3, 8, 2, 5, 1, 6, 9])

In [ ]:
a.sort() # Sorting is performed inplace using sort() function

In [ ]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a = np.array([[23,4,43], [12, 89, 3], [69, 420, 0]])

In [ ]:
a.ndim

2

In [ ]:
a.shape

(3, 3)

In [ ]:
np.sort(a) # Default is last axis, i.e., axis=1

array([[  4,  23,  43],
       [  3,  12,  89],
       [  0,  69, 420]])

In [ ]:
np.sort(a, axis=0) # Sorts 2D numpy array columnwise

array([[ 12,   4,   0],
       [ 23,  89,   3],
       [ 69, 420,  43]])

In [ ]:
np.sort(a, axis=-1) # Doesn't work

array([[  4,  23,  43],
       [  3,  12,  89],
       [  0,  69, 420]])

In [ ]:
a

array([[ 23,   4,  43],
       [ 12,  89,   3],
       [ 69, 420,   0]])

In [ ]:
-a

array([[ -23,   -4,  -43],
       [ -12,  -89,   -3],
       [ -69, -420,    0]])

In [ ]:
np.sort(-a)

array([[ -43,  -23,   -4],
       [ -89,  -12,   -3],
       [-420,  -69,    0]])

In [ ]:
z = -np.sort(-a)

In [ ]:
z # Why this is wrong? Think.

array([[ 43,  23,   4],
       [ 89,  12,   3],
       [420,  69,   0]])

In [ ]:
np.sort(a)[:,::-1]

array([[ 43,  23,   4],
       [ 89,  12,   3],
       [420,  69,   0]])

In [ ]:
## Element-Wise Multiplication

In [ ]:
a = np.arange(5)
b = np.ones(5) # np.ones gives a numpy array of ones, np.zeros gives the same for zeros, np.zeros()

In [ ]:
print(a)

[0 1 2 3 4]


In [ ]:
print(b)

[1. 1. 1. 1. 1.]


In [ ]:
a * b

array([0., 1., 2., 3., 4.])

In [ ]:
a = np.array([2,3,4,5,6])
b = np.array([1,2,3,4,5])

In [ ]:
a * b

array([ 2,  6, 12, 20, 30])

In [ ]:
a = np.arange(1,13).reshape(3,4)

In [ ]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
b = np.arange(2,14).reshape(3,4)

In [ ]:
b

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [ ]:
a * b

array([[  2,   6,  12,  20],
       [ 30,  42,  56,  72],
       [ 90, 110, 132, 156]])

In [ ]:
b = np.arange(2,14).reshape(4,3)

In [ ]:
b

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13]])

In [ ]:
a * b

ValueError: ignored

In [ ]:
## Matrix Multiplication

In [ ]:
# No. of columns of first matrix == No. of rows of second matrix

In [ ]:
a = np.arange(1,13).reshape((3,4)) # 3x4 matrix
c = np.arange(2,14).reshape((4,3)) # 4x3 matrix

In [ ]:
a.shape

(3, 4)

In [ ]:
c.shape

(4, 3)

In [ ]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
c

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13]])

In [ ]:
np.dot(a,c)

array([[ 80,  90, 100],
       [184, 210, 236],
       [288, 330, 372]])

In [ ]:
np.matmul(a,c)

array([[ 80,  90, 100],
       [184, 210, 236],
       [288, 330, 372]])

In [ ]:
a@c

array([[ 80,  90, 100],
       [184, 210, 236],
       [288, 330, 372]])

In [ ]:
5 * a

array([[ 5, 10, 15, 20],
       [25, 30, 35, 40],
       [45, 50, 55, 60]])

In [ ]:
np.dot(5,a) # Can do elementwise operation

array([[ 5, 10, 15, 20],
       [25, 30, 35, 40],
       [45, 50, 55, 60]])

In [ ]:
np.matmul(5,a)

ValueError: ignored

In [ ]:
5@a

ValueError: ignored

In [ ]:
A = np.arange(10).reshape(5,2)
B = np.arange(2).reshape(2,1)
print(np.dot(A,B))

[[1]
 [3]
 [5]
 [7]
 [9]]


In [ ]:
A

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [ ]:
B

array([[0],
       [1]])

In [ ]:
# Vectorization

In [ ]:
a=np.arange(1,13)

In [ ]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
a*2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24])

In [ ]:
def saptarshi(x):
  if (x%2 == 0):
    x += 2
  else:
    x += 3
  return x

In [ ]:
saptarshi(5)

8

In [ ]:
saptarshi(a)

ValueError: ignored

In [ ]:
func = np.vectorize(saptarshi)

In [ ]:
func(a)

array([ 4,  4,  6,  6,  8,  8, 10, 10, 12, 12, 14, 14])

In [ ]:
import math
func1 = np.vectorize(math.log)

In [ ]:
func1(a)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665])

In [ ]:
a = np.tile(np.arange(0,40,10), (3,1)) # np.tile(array, reps)

In [ ]:
a

array([[ 0, 10, 20, 30],
       [ 0, 10, 20, 30],
       [ 0, 10, 20, 30]])

In [ ]:
a = np.tile(np.arange(0,40,10).T, (3,1))

In [ ]:
a

array([[ 0, 10, 20, 30],
       [ 0, 10, 20, 30],
       [ 0, 10, 20, 30]])

In [ ]:
a = np.tile(np.arange(0,40,10), (3,2)) # np.tile(array, reps)

In [ ]:
a

array([[ 0, 10, 20, 30,  0, 10, 20, 30],
       [ 0, 10, 20, 30,  0, 10, 20, 30],
       [ 0, 10, 20, 30,  0, 10, 20, 30]])

In [ ]:
a.shape

(3, 8)

In [ ]:
b = np.tile(np.arange(0,3), (4,1)) # np.tile(array, reps)

In [ ]:
a

array([[ 0, 10, 20, 30],
       [ 0, 10, 20, 30],
       [ 0, 10, 20, 30]])

In [ ]:
a = a.T

In [ ]:
a

array([[ 0,  0,  0],
       [10, 10, 10],
       [20, 20, 20],
       [30, 30, 30]])

In [ ]:
b

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [ ]:
b = np.arange(0,3)

In [ ]:
b

array([0, 1, 2])

In [ ]:
a + b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [ ]:
b

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [ ]:
a + b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [ ]:
a = np.arange(0,40,10).reshape(4,1)

In [ ]:
a

array([[ 0],
       [10],
       [20],
       [30]])

In [ ]:
b = np.arange(0,3)

In [ ]:
b

array([0, 1, 2])

In [ ]:
a.ndim

2

In [ ]:
b.ndim

1

In [ ]:
a.shape

(4, 1)

In [ ]:
b.shape

(3,)

In [ ]:
a + b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [ ]:
A = np.arange(12).reshape(3, 4)

In [ ]:
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
B = np.array([1, 2, 3])

In [ ]:
A + B

ValueError: ignored

In [ ]:
# Element wise multiplication
Array * number -> Works
Array * Array (same shape) -> Works
Array * Array (different shape) -> Doesn't work

SyntaxError: ignored

In [ ]:
#Broadcasting rules
'''
Rule1: If dimensions in both matrix are equal, element wise addition will be done
Rule2: If right array is 1D and no of columns is same for both arrays, it will automatically do n-tile
Rule3: If left array is column matrix (1 column only) and right array is row matrix (1 row), then it will do n-tile for both matrices
'''

'\nRule1: If dimensions in both matrix are equal, element wise addition will be done\nRule2: If right array is 1D and no of columns is same for both arrays, it will automatically do n-tile\nRule3: If left array is column matrix (1 column only) and right array is row matrix (1 row), then it will do n-tile for both matrices\n'

In [ ]:
'''
A -> (8,1,6,1)
B -> (7,1,5)

No. of dimensions not equal, so shape of B becomes -> (1,7,1,5)
A -> (8,1,6,1)
B -> (1,7,1,5)

# Appends dimension at left column

Output shape becomes -> (8,7,6,5)
'''

'\nA -> (8,1,6,1)\nB -> (7,1,5)\n\nNo. of dimensions not equal, so shape of B becomes -> (1,7,1,5)\nA -> (8,1,6,1)\nB -> (1,7,1,5)\n\nOutput shape becomes -> (8,7,6,5)\n'

In [ ]:
x = np.array([1,2,3])
x += np.array([5])

In [ ]:
x

array([6, 7, 8])

In [ ]:
x = np.array([[1,2],[3,4]])

In [ ]:
x

array([[1, 2],
       [3, 4]])

In [ ]:
x.shape

(2, 2)

In [ ]:
y = np.array([5,6])

In [ ]:
y.shape

(2,)

In [ ]:
x + y

array([[ 6,  8],
       [ 8, 10]])

In [ ]:
import numpy as np
p = np.array([[0,1], [10,11], [20,22]])
q = np.array([10, 11, 12])

In [ ]:
p

array([[ 0,  1],
       [10, 11],
       [20, 22]])

In [ ]:
q

array([10, 11, 12])

In [ ]:
p+q

ValueError: ignored

In [ ]:
q.shape

(3,)

In [ ]:
p.shape

(3, 2)